declare module 'is-hexcolor';
declare module 'search-npm-registry';
declare module 'weather-js';
declare module 'random-puppy'
declare module 'superagent'
declare module 'yt-search'
declare module 'node-tesseract-ocr'
declare module 'youtube-search-engine'
declare module 'axmap'